import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
export default function Page() {
  return <div>သင်္ချာ မိတ်ဆက်ခြင်း</div>;
}
