import YearPlan from "@/components/courses/grade-12/english/year-plan";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 7 English လပိုင်းမာတိကာ",
  description: "Generated by create next app",
};
export default function Page() {
  return <YearPlan />;
}
