import { Metadata } from "next";
import question1 from "@/datas/grade-12/mathematics/pass-questions/2024/question1.json";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};

import { InlineMath } from "react-katex";
import { QuestionItem, SelectAnswer } from "@/components/courses/questions";

export default function Page() {
  return (
    <div className="flex w-full flex-col break-words">
      {question1.set1.map((data) => (
        <div
          key={data["question-item-number"]}
          className="flex max-w-screen flex-col"
        >
          <QuestionItem>
            <InlineMath math={data["question-item-number"]} />
            <div className="break-words text-base flex flex-wrap ">
              <InlineMath math={data["question-item-text"]} />
            </div>
          </QuestionItem>
          <SelectAnswer>
            {data.options.map((option, index) => (
              <InlineMath key={index} math={option} />
            ))}
          </SelectAnswer>
        </div>
      ))}
    </div>
  );
}
