import {
  Exercise,
  Lesson,
  Skill,
  Unit,
} from "@/components/courses/english/english";
import { RightAppSidebar } from "@/components/right-sidebar";
import { SidebarProvider } from "@/components/ui/right-sidebar";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 6 English Text Keys Unit 1",
  description: "Generated by create next app",
};
const items = [
  {
    url: "#lesson-1",
    lesson: "Lesson 1",
    title: "What does he look like?",
  },
  { url: "#lesson-2", lesson: "Lesson 2", title: "What’s she wearing?" },
  {
    url: "#lesson-3",
    lesson: "Lesson 3",
    title: "Who’s the tallest?",
  },
  { url: "#lesson-4", lesson: "Lesson 4", title: "Find someone who ..." },
];
export default function Page() {
  return (
    <SidebarProvider className="w-full">
      <div className="w-full">
        <div id="lesson-1" className="w-full min-h-screen">
          <Unit>Unit 7</Unit>
          <Lesson>Lesson 1 : What does he look like?</Lesson>
          <Skill>Listening</Skill>
          <Exercise>Exercise 2</Exercise>
          <div>Aung Aung, Su Hlaing, Yangon, Bye!,See You!</div>
        </div>
        <div id="lesson-2" className="w-full min-h-screen">
          <Lesson>Lesson 2 : What’s she wearing?</Lesson>
          <Skill>Reading</Skill>
          <Exercise>Exercise 1</Exercise>
        </div>
        <div id="lesson-3" className="w-full min-h-screen">
          <Lesson>Lesson 3 : Who’s the tallest?</Lesson>
          <Skill>Vocabulary</Skill>
          <Exercise>Exercise 1</Exercise>
        </div>
        <div id="lesson-4" className="w-full min-h-screen">
          <Lesson>Lesson 4 : Find someone who ...</Lesson>
          <Skill>Writing</Skill>
          <Exercise>Exercise 1</Exercise>
        </div>
      </div>
      <RightAppSidebar items={items} />
    </SidebarProvider>
  );
}
