import type { Metadata } from "next";
import { categories } from "@/datas/grade-12/mathematics/categories.json";
import { steams1 } from "@/datas/high/subjects.json";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import {
  AppContent,
  AppSidebar,
  AppSidebarNav,
} from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Grade 12 ",
  description: "Generated by create next app",
};

export default function Grade12Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <SidebarProvider>
        <AppSidebar
          data={categories}
          teams={steams1}
          activeTeam={steams1.subjects[2]}
        />
        <SidebarInset>
          <AppSidebarNav />
          <AppContent>{children}</AppContent>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
}
