import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 6 Myanmar",
  description: "Generated by create next app",
};
export default function Page() {
  return <div>အင်္ဂလိပ်စာ မိတ်ဆက်ခြင်း</div>;
}
