import {
  ContentHeader,
  ContentSubHeader,
} from "@/components/courses/grade-12/mathematics/mathematics";
import { Card } from "@/components/ui/card";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
import { InlineMath } from "react-katex";
export default function Page() {
  return (
    <div className="w-full">
      <h1 className="text-center py-3 text-3xl font-bold">
        ဒွါဒသမတန်း သင်္ချာ မိတ်ဆက်ခြင်း
      </h1>
      <Card className="px-3">
        <ContentHeader>
          <p>1</p>
          <p>Complex Number</p>
        </ContentHeader>
        <ContentSubHeader>
          <p>1.1</p>
          <p>
            Pure Imaginary Unit <InlineMath>i</InlineMath>
          </p>
        </ContentSubHeader>
        <ContentSubHeader>
          <p>1.2</p>
          <p>
            Complex Number <InlineMath>(x,y)</InlineMath>
          </p>
        </ContentSubHeader>
        <ContentSubHeader>
          <p>1.3</p>
          <p>Opreations on Complex Numbers</p>
        </ContentSubHeader>
      </Card>
    </div>
  );
}
