import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Us - Alinn Education",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <div className="bg-orange-800 w-full h-60"></div>
      <div className="flex flex-row justify-around">
        <div className="w-16 h-16 bg-blue-900 rounded-full flex text-4xl items-center justify-center">
          f
        </div>
        <div className="w-16 h-16 bg-blue-900 rounded-full"></div>
        <div className="w-16 h-16 bg-blue-900 rounded-full"></div>
        <div className="w-16 h-16 bg-blue-900 rounded-full"></div>
      </div>
    </div>
  );
};

export default page;
