"use client";
import type { Metadata } from "next";
import { stams, steams2 } from "@/datas/high/subjects.json";
import { categories } from "@/datas/grade-10/economic/categories.json";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import {
  AppSidebar,
  AppSidebarNav,
  AppContent,
} from "@/components/app-sidebar";
import { useSearchParams } from "next/navigation";
import { useGradeTypeStore } from "@/store/useGradeTypeStore";

// export const metadata: Metadata = {
//   title: "Grade 12 ",
//   description: "Generated by create next app",
// };

export default function Grade12Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { gradeType } = useGradeTypeStore();
  return (
    <SidebarProvider>
      <AppSidebar
        data={categories}
        teams={gradeType === "stams" ? stams : steams2}
        activeTeam={stams.subjects[5]}
      />
      <SidebarInset>
        <AppSidebarNav />
        <AppContent>{children}</AppContent>
      </SidebarInset>
    </SidebarProvider>
  );
}
