import {
  TableBody,
  TableData,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/layouts/table";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 7 English လပိုင်းမာတိကာ",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div>
      <h1>စာရိတ္တနှင့် ပြည်သူ့နီတိ လပိုင်းမာတိကာ</h1>
      <table className="table-auto table border-2 w-full text-sm md:text-base">
        <TableHeader>
          <TableRow>
            <TableHead>သတင်းပတ်</TableHead>
            <TableHead>အချိန်</TableHead>
            <TableHead>အခန်းခေါင်းစဉ်</TableHead>
            <TableHead>သင်ခန်းစာခေါင်းစဉ်</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow>
            <TableData>၁</TableData>
            <TableData>၁</TableData>
            <TableData>၁</TableData>
            <TableData>၁</TableData>
          </TableRow>
        </TableBody>
      </table>
    </div>
  );
}
