import PassQuestion from "@/components/courses/grade-12/myanmar/pass-questions/pass-question";
import question1a from "@/datas/grade-12/myanmar/pass-questions/2024/question1a.json";
import question1b from "@/datas/grade-12/myanmar/pass-questions/2024/question1b.json";
import question1c from "@/datas/grade-12/myanmar/pass-questions/2024/question1c.json";
import question2 from "@/datas/grade-12/myanmar/pass-questions/2024/question2.json";
import question3 from "@/datas/grade-12/myanmar/pass-questions/2024/question3.json";
import question4 from "@/datas/grade-12/myanmar/pass-questions/2024/question4.json";
import question5 from "@/datas/grade-12/myanmar/pass-questions/2024/question5.json";
import question6 from "@/datas/grade-12/myanmar/pass-questions/2024/question6.json";
import question7 from "@/datas/grade-12/myanmar/pass-questions/2024/question7.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div>
      <PassQuestion
        year="၂၀၂၄ ခုနှစ်"
        question1a={question1a.set3}
        question1b={question1b.set3}
        question1c={question1c.set3}
        question2={question2.set3}
        question3={question3.set3}
        question4={question4.set3}
        question5={question5.set3}
        question6={question6.set3}
        question7={question7.set3}
      />
    </div>
  );
}
