import {
  TableBody,
  TableData,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/middle/year-plan";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 7 English လပိုင်းမာတိကာ",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <table className="table-auto table border-2 w-full">
      <TableHeader>
        <TableRow>
          <TableHead>Unit</TableHead>
          <TableHead>Lesson</TableHead>
          <TableHead>Topic</TableHead>
          <TableHead>Period</TableHead>
          <TableHead>
            <p>Total</p>
            <p> Periods </p>
            <p>for each </p>
            <p>unit</p>
          </TableHead>
          <TableHead>Schedule</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {/* Unit 1 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 1</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Do you have good eating habits?
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={7}>June</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Learning starts at home
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Busy dad!
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            A day-to-day work routine
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 2 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 2</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            At a new school
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            School
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Who teaches you English?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            The best school in town
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={8}>July</TableData>
        </TableRow>
        {/* Unit 3 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 3</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Which activity do you like doing most?
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            I love knitting
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Could I have a piece of cheesecake?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Let's play in the school band!
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Review , Project and Poem (1) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 1</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 1</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 1</TableData>
          <TableData align="left" className="pl-5">
            On the Vowels
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        {/* Unit 4 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 4</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            What kind of person are you?
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={6}>August</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            A global citizen
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            The best of the best
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            People around me
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 5 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 5</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Do you know how to use a computer?
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Basics of a computer
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Take the medicine three times a day
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={7}>September</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Let's try these experiments!
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 6 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 6</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Our environment
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Our friendly environment
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Environmentally-friendly lifestyle
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Let's save our earth!
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Review , Project and Poem (2) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 2</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 2</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={6}>October</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 2</TableData>
          <TableData align="left" className="pl-5">
            How Beautiful is the Rain!
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        {/* Unit 7 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 7</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Who is calling, please?
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Are you planning a holiday?
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            What are you going to do this weekend?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Camping and trekking
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 8 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 8</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            A weekend at a resort
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={7}>November</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Heaven or Paradise?
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Which is a better resort?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            My dream resort
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 9 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 9</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            What is the biggest lake in Myanmar?
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Beautiful Myanmar
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            An ideal place for a day trip
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            A memorable holiday
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={8}>December</TableData>
        </TableRow>
        {/* Review , Project and Poem (3) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 3</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 3</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 3</TableData>
          <TableData align="left" className="pl-5">
            The Snare
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        {/* Unit 10 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 10</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            My favourite pastime
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            More time to relax
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            What do you like doing in your free time?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            A happy healthy family
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 11 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 11</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            My favourite digital device
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={7}>January</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Do you have a mobile phone?
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            I will buy a new laptop if ...
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            I will send you a text message
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 12 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 12</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Breaking news
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            What is happening in the world today?
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Good news or bad news?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            What happened in my neighbourhood?
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={4}>February</TableData>
        </TableRow>
        {/* Review , Project and Poem (4) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 4</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 4</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 4</TableData>
          <TableData align="left" className="pl-5">
            The Moon
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left" className="pl-5" colSpan={3}>
            Total (Teaching periods)
          </TableData>
          <TableData>188</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left" className="pl-5" colSpan={3}>
            Reserve(revision and exam)
          </TableData>
          <TableData>28</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left" className="pl-5 font-bold" colSpan={3}>
            Total
          </TableData>
          <TableData className="font-bold">216</TableData>
        </TableRow>
      </TableBody>
    </table>
  );
}
