import GradeCard from "@/components/GradeCard";
import grades from "data/grades.json";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "All Courses - Alinn Education",
  description: "Generated by create next app",
};
const Grade = () => {
  redirect("./courses/grade-12");
  return (
    <div className="grid w-full grid-cols-4  mx-atuo items-center bg-amber-900">
      {grades.map((grade) => (
        <div key={grade.id}>
          <GradeCard grade={grade} />
        </div>
      ))}
    </div>
  );
};

export default Grade;
