import PassQuestion from "@/components/courses/grade-12/myanmar/pass-questions/pass-question";
import question1a from "@/datas/grade-12/myanmar/pass-questions/2025/question1a.json";
import question1b from "@/datas/grade-12/myanmar/pass-questions/2025/question1b.json";
import question1c from "@/datas/grade-12/myanmar/pass-questions/2025/question1c.json";
import question2 from "@/datas/grade-12/myanmar/pass-questions/2025/question2.json";
import question3 from "@/datas/grade-12/myanmar/pass-questions/2025/question3.json";
import question4 from "@/datas/grade-12/myanmar/pass-questions/2025/question4.json";
import question5 from "@/datas/grade-12/myanmar/pass-questions/2025/question5.json";
import question6 from "@/datas/grade-12/myanmar/pass-questions/2025/question6.json";
import question7 from "@/datas/grade-12/myanmar/pass-questions/2025/question7.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div>
      <PassQuestion
        year="၂၀၂၅ ခုနှစ်"
        question1a={question1a.set11}
        question1b={question1b.set11}
        question1c={question1c.set11}
        question2={question2.set11}
        question3={question3.set11}
        question4={question4.set11}
        question5={question5.set11}
        question6={question6.set11}
        question7={question7.set11}
      />
    </div>
  );
}
