import { Set2 } from "@/components/courses/grade-12/myanmar/pass-questions/2024/sets";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
export default function Page() {
  return <Set2 />;
}
