import PassQuestion from "@/components/courses/grade-12/biology/pass-questions/pass-question";
import question1 from "@/datas/grade-12/biology/pass-questions/2025/question1.json";
import question2 from "@/datas/grade-12/biology/pass-questions/2025/question2.json";
import question3 from "@/datas/grade-12/biology/pass-questions/2025/question3.json";
import question4 from "@/datas/grade-12/biology/pass-questions/2025/question4.json";
import question5 from "@/datas/grade-12/biology/pass-questions/2025/question5.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "ဒွါဒသမတန်း အင်္ဂလိပ်စာ ၂၀၂၄ မေးခွန်း(၁)",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set2}
        question2={question2.set2}
        question3={question3.set2}
        question4={question4.set2}
        question5={question5.set2}
      />
    </div>
  );
}
