"use client";
import type { Metadata } from "next";
import { stams, steams1, steams2 } from "@/datas/high/subjects.json";
import { categories } from "@/datas/grade-12/mathematics/categories.json";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import "katex/dist/katex.min.css";
import {
  AppSidebar,
  AppSidebarNav,
  AppContent,
} from "@/components/app-sidebar";
import { useGradeTypeStore } from "@/store/useGradeTypeStore";

// export const metadata: Metadata = {
//   title: "Grade 12 ",
//   description: "Generated by create next app",
// };

export default function Grade12Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { gradeType } = useGradeTypeStore();
  return (
    <SidebarProvider>
      <AppSidebar
        data={categories}
        teams={
          gradeType === "stams"
            ? stams
            : gradeType === "steams2"
            ? steams2
            : steams1
        }
        activeTeam={stams.subjects[2]}
      />
      <SidebarInset>
        <AppSidebarNav />
        <AppContent>{children}</AppContent>
      </SidebarInset>
    </SidebarProvider>
  );
}
