import PassQuestion from "@/components/courses/grade-12/english/pass-questions/pass-question";
import question1 from "@/datas/grade-12/english/pass-questions/2025/question1.json";
import question2 from "@/datas/grade-12/english/pass-questions/2025/question2.json";
import question3 from "@/datas/grade-12/english/pass-questions/2025/question3.json";
import question4a from "@/datas/grade-12/english/pass-questions/2025/question4a.json";
import question4b from "@/datas/grade-12/english/pass-questions/2025/question4b.json";
import question5 from "@/datas/grade-12/english/pass-questions/2025/question5.json";
import question6 from "@/datas/grade-12/english/pass-questions/2025/question6.json";
import question7a from "@/datas/grade-12/english/pass-questions/2025/question7a.json";
import question7b from "@/datas/grade-12/english/pass-questions/2025/question7b.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
export function Set1() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set1}
        question2={question2.set1}
        question3={question3.set1}
        question4a={question4a.set1}
        question4b={question4b.set1}
        question5={question5.set1}
        question6={question6.set1}
        question7a={question7a.set1}
        question7b={question7b.set1}
      />
    </div>
  );
}
export function Set2() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set2}
        question2={question2.set2}
        question3={question3.set2}
        question4a={question4a.set2}
        question4b={question4b.set2}
        question5={question5.set2}
        question6={question6.set2}
        question7a={question7a.set2}
        question7b={question7b.set2}
      />
    </div>
  );
}

export function Set3() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set3}
        question2={question2.set3}
        question3={question3.set3}
        question4a={question4a.set3}
        question4b={question4b.set3}
        question5={question5.set3}
        question6={question6.set3}
        question7a={question7a.set3}
        question7b={question7b.set3}
      />
    </div>
  );
}
export function Set4() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set4}
        question2={question2.set4}
        question3={question3.set4}
        question4a={question4a.set4}
        question4b={question4b.set4}
        question5={question5.set4}
        question6={question6.set4}
        question7a={question7a.set4}
        question7b={question7b.set4}
      />
    </div>
  );
}
export function Set5() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set5}
        question2={question2.set5}
        question3={question3.set5}
        question4a={question4a.set5}
        question4b={question4b.set5}
        question5={question5.set5}
        question6={question6.set5}
        question7a={question7a.set5}
        question7b={question7b.set5}
      />
    </div>
  );
}
export function Set6() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set6}
        question2={question2.set6}
        question3={question3.set6}
        question4a={question4a.set6}
        question4b={question4b.set6}
        question5={question5.set6}
        question6={question6.set6}
        question7a={question7a.set6}
        question7b={question7b.set6}
      />
    </div>
  );
}
export function Set7() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set7}
        question2={question2.set7}
        question3={question3.set7}
        question4a={question4a.set7}
        question4b={question4b.set7}
        question5={question5.set7}
        question6={question6.set7}
        question7a={question7a.set7}
        question7b={question7b.set7}
      />
    </div>
  );
}
export function Set8() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set8}
        question2={question2.set8}
        question3={question3.set8}
        question4a={question4a.set8}
        question4b={question4b.set8}
        question5={question5.set8}
        question6={question6.set8}
        question7a={question7a.set8}
        question7b={question7b.set8}
      />
    </div>
  );
}
export function Set9() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set9}
        question2={question2.set9}
        question3={question3.set9}
        question4a={question4a.set9}
        question4b={question4b.set9}
        question5={question5.set9}
        question6={question6.set9}
        question7a={question7a.set9}
        question7b={question7b.set9}
      />
    </div>
  );
}
export function Set10() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set10}
        question2={question2.set10}
        question3={question3.set10}
        question4a={question4a.set10}
        question4b={question4b.set10}
        question5={question5.set10}
        question6={question6.set10}
        question7a={question7a.set10}
        question7b={question7b.set10}
      />
    </div>
  );
}
