import type { Metadata } from "next";
import subjects from "@/datas/primary/subjects.json";
import { categories } from "@/public/category/grade-1/english/categories.json";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import {
  AppContent,
  AppSidebar,
  AppSidebarNav,
} from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Grade 1",
  description: "Generated by create next app",
};

export default function Grade12Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar
        data={categories}
        teams={subjects}
        activeTeam={subjects.subjects[1]}
      />
      <SidebarInset>
        <AppSidebarNav />
        <AppContent>{children}</AppContent>
      </SidebarInset>
    </SidebarProvider>
  );
}
