import {
  TableBody,
  TableData,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/layouts/year-plan";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 7 English လပိုင်းမာတိကာ",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <table className="table-auto table border-2 w-full text-sm md:text-base">
      <TableHeader>
        <TableRow>
          <TableHead>Unit</TableHead>
          <TableHead>Lesson</TableHead>
          <TableHead>Topic</TableHead>
          <TableHead>Period</TableHead>
          <TableHead>
            <p>Total</p>
            <p> Periods </p>
            <p>for each </p>
            <p>unit</p>
          </TableHead>
          <TableHead>Schedule</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {/* Unit 1 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 1</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Greeting, introducing and leave-taking
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={7}>June</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Greetings from postcards
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Greetings for special events
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Let&lsquos send a postcard
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 2 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 2</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Tell me about families
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Talking about families
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            My best friend
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Daily routine
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={8}>July</TableData>
        </TableRow>
        {/* Unit 3 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 3</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Talking about your city
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            At the market
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            What is it?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            My favourite room
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Review , Project and Poem (1) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 1</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 1</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 1</TableData>
          <TableData align="left" className="pl-5">
            The Owl
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        {/* Unit 4 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 4</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Talking about your family and free time
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={6}>August</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            A happy family
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Talking about habits and routines
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            What we like and dislike!
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 5 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 5</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Where shall we meet?
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Let’s read a short note!
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Where are you from?
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={7}>September</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Filling in a form
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 6 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 6</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Let’s eat out!
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Do you eat healthy food?
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            <p>What’s the difference: countable and </p>
            <p>uncountable?</p>
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Let’s go shopping!
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Review , Project and Poem (2) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 2</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 2</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={6}>October</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 2</TableData>
          <TableData align="left" className="pl-5">
            Early to bed and early to rise
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        {/* Unit 7 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 7</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            What does he look like?
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            What is she wearing?
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Who is the tallest?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Find someone who ...
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 8 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 8</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            How much is it?
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={7}>November</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Look at this leaflet!
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            How much do you want?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Happy birthday!
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 9 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 9</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Requesting
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            My favourite possessions
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            This is mine!
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Does this pen belong to you?
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={8}>December</TableData>
        </TableRow>
        {/* Review , Project and Poem (3) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 3</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 3</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 3</TableData>
          <TableData align="left" className="pl-5">
            The rainbow
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        {/* Unit 10 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 10</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Sport is great!
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            A myanmar lady sport star to admire
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            We are doing sports
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            A sports star I like
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 11 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 11</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            I love my school
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={7}>January</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Our school keeps discipline
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Must or Can?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            A phone message
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 12 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 12</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Shapes
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            The Tin Man looking for a heart
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            What shape is it?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Can you describe it?
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={4}>February</TableData>
        </TableRow>
        {/* Review , Project and Poem (4) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 4</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 4</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 4</TableData>
          <TableData align="left" className="pl-5">
            The butterfly
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={3}> </TableData>
          <TableData rowSpan={3}> </TableData>
          <TableData align="left" className="pl-5">
            Total (Teaching periods)
          </TableData>
          <TableData> </TableData>
          <TableData>188</TableData>
          <TableData rowSpan={3}> </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left" className="pl-5">
            Reserve(revision and exam)
          </TableData>
          <TableData> </TableData>
          <TableData>28</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left" className="pl-5 font-bold">
            Total
          </TableData>
          <TableData> </TableData>
          <TableData className="font-bold">216</TableData>
        </TableRow>
      </TableBody>
    </table>
  );
}
