import {
  Exercise,
  Lesson,
  Skill,
  Unit,
} from "@/components/courses/english/english";
import { AppContent, RightAppSidebar } from "@/components/right-sidebar";
import { SidebarProvider } from "@/components/ui/right-sidebar";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 6 English Text Keys Unit 1",
  description: "Generated by create next app",
};
const items = [
  {
    url: "#lesson-1",
    lesson: "Lesson 1",
    title: "How much is it?",
  },
  { url: "#lesson-2", lesson: "Lesson 2", title: "Look at this leaflet!" },
  {
    url: "#lesson-3",
    lesson: "Lesson 3",
    title: "How much do you want?",
  },
  { url: "#lesson-4", lesson: "Lesson 4", title: "Happy Birthday!" },
];
export default function Page() {
  return (
    <SidebarProvider className="w-full">
      <div className="w-full">
        <div id="lesson-1" className="w-full min-h-screen">
          <Unit>Unit 8</Unit>
          <Lesson>Lesson 1 : How much is it?</Lesson>
          <Skill>Listening</Skill>
          <Exercise>Exercise 2</Exercise>
          <div>Aung Aung, Su Hlaing, Yangon, Bye!,See You!</div>
        </div>
        <div id="lesson-2" className="w-full min-h-screen">
          <Lesson>Lesson 2 : Look at this leaflet!</Lesson>
          <Skill>Reading</Skill>
          <Exercise>Exercise 1</Exercise>
        </div>
        <div id="lesson-3" className="w-full min-h-screen">
          <Lesson>Lesson 3 : How much do you want?</Lesson>
          <Skill>Vocabulary</Skill>
          <Exercise>Exercise 1</Exercise>
        </div>
        <div id="lesson-4" className="w-full min-h-screen">
          <Lesson>Lesson 4 : Happy Birthday!</Lesson>
          <Skill>Writing</Skill>
          <Exercise>Exercise 1</Exercise>
        </div>
      </div>
      <RightAppSidebar items={items} />
    </SidebarProvider>
  );
}
