import {
  Exercise,
  Key,
  Lesson,
  Skill,
  Unit,
} from "@/components/courses/english/english";
import {
  TableBody,
  TableData,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/layouts/table";
import { RightAppSidebar } from "@/components/right-sidebar";
import { SidebarProvider } from "@/components/ui/right-sidebar";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 6 English Text Keys Unit 1",
  description: "Generated by create next app",
};
const items = [
  {
    url: "#lesson-1",
    lesson: "Lesson 1",
    title: "Greeting, introducing and leave-taking",
  },
  { url: "#lesson-2", lesson: "Lesson 2", title: "Greetings from postcards" },
  {
    url: "#lesson-3",
    lesson: "Lesson 3",
    title: "Greetings for special events",
  },
  { url: "#lesson-4", lesson: "Lesson 4", title: "Let’s send a postcard!" },
];
export default function Page() {
  return (
    <SidebarProvider className="w-full">
      <div className="w-full">
        <div id="lesson-1" className="w-full">
          <Unit>Unit 1</Unit>
          <Lesson>Lesson 1 : Greeting, introducing and leave-taking</Lesson>
          <Skill>Listening</Skill>
          <Exercise>Exercise 2</Exercise>
          <Key>Aung Aung, Su Hlaing, Yangon, Bye!,See You!</Key>
          <Exercise>Exercise 5</Exercise>
          <Key>
            May Thu, Su Su, Nyi Lay, Mandalay, Yangon, Excuse me!, Goodbye.,
            Bye!
          </Key>
          <Skill>Speaking</Skill>
          <Exercise>Exercise 1</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <div className="text-nowrap">1. b</div>
              <div className="text-nowrap">2. g</div>
              <div className="text-nowrap">3. f</div>
              <div className="text-nowrap">4. d</div>
              <div className="text-nowrap">5. c</div>
              <div className="text-nowrap">6. a</div>
              <div className="text-nowrap">7. e</div>
            </div>
          </Key>
        </div>
        <div id="lesson-2" className="w-full">
          <Lesson>Lesson 2 : Greetings from postcards</Lesson>
          <Skill>Reading</Skill>
          <Exercise>Exercise 1</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">1. seashells</p>
              <p className="text-nowrap">2. cave</p>
              <p className="text-nowrap">3. seagull</p>
              <p className="text-nowrap">4. crab</p>
              <p className="text-nowrap">5. waterfall</p>
              <p className="text-nowrap">6. palace</p>
              <p className="text-nowrap">7. prawn</p>
              <p className="text-nowrap">8. backpack</p>
            </div>
          </Key>
          <Exercise>Exercise 2a</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">1. Ngapali</p>
              <p className="text-nowrap">2. Pyin Oo Lwin</p>
              <p className="text-nowrap">3. Shwebo</p>
            </div>
          </Key>
          <Exercise>Exercise 2b</Exercise>
          <Key>Postcard 2</Key>
          <Exercise>Exercise 3</Exercise>
          <Key>
            <table className="table-auto table border-2 w-full text-sm md:text-base">
              <TableHeader>
                <TableRow>
                  <TableHead>Postcard</TableHead>
                  <TableHead>From Whom</TableHead>
                  <TableHead>To Whom</TableHead>
                  <TableHead>Food and drink</TableHead>
                  <TableHead>Weather</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableData>2</TableData>
                  <TableData>Tin Zar</TableData>
                  <TableData>Zin Mi Mi Lwin / Zin Zin</TableData>
                  <TableData>strawberries</TableData>
                  <TableData>cool and pleasant</TableData>
                </TableRow>
                <TableRow>
                  <TableData>3</TableData>
                  <TableData>Thura</TableData>
                  <TableData>U Tun Aung / Mum and Dad</TableData>
                  <TableData>peas and beans</TableData>
                  <TableData>fine</TableData>
                </TableRow>
                <TableRow>
                  <TableData>1</TableData>
                  <TableData>Mie Mie</TableData>
                  <TableData>Kay Khine / Kay Kay</TableData>
                  <TableData>crabs and prawns</TableData>
                  <TableData>sunny and breezy</TableData>
                </TableRow>
              </TableBody>
            </table>
          </Key>
          <Exercise>Exercise 4</Exercise>
          <Key>
            <div className="flex">
              <p>1.</p>
              <p>Mie Mie picked up seashells along the shore at Ngapali.</p>
            </div>
            <div className="flex">
              <p>2.</p>
              <p>
                Mie Mie ate crabs and prawns there because they were fresh and
                delicious.
              </p>
            </div>
            <div className="flex">
              <p>3.</p>
              <p>
                The weather is cool and pleasant in Pyin Oo Lwin in December.
              </p>
            </div>
            <div className="flex">
              <p>4.</p>
              <p>
                The interesting places in Shwebo are Hanlin, an ancient city,
                Maha Nandar Lake and the old palace.
              </p>
            </div>
            <div className="flex">
              <p>5.</p>
              <p>
                Thura thought he was getting stronger because he could carry his
                heavy backpack easily.
              </p>
            </div>
          </Key>
        </div>
        <div id="lesson-3" className="w-full">
          <Lesson>Lesson 3 : Greetings for special events</Lesson>
          <Skill>Vocabulary</Skill>
          <Exercise>Exercise 1</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">a. Happy Birthday!</p>
              <p className="text-nowrap">b. Merry X&apos;mas</p>
              <p className="text-nowrap">c. Happy New Year!</p>
              <p className="text-nowrap">d. Get Well Soon!</p>
              <p className="text-nowrap">e. Happy Holiday!</p>
            </div>
          </Key>{" "}
          <Exercise>Exercise 2</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">a. cloudly</p>
              <p className="text-nowrap">b. rainy</p>
              <p className="text-nowrap">c. snowy</p>
              <p className="text-nowrap">d. sunny</p>
              <p className="text-nowrap">e. windly</p>
            </div>
          </Key>
          <Exercise>Exercise 3</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">1. windly</p>
              <p className="text-nowrap">2. snowy</p>
              <p className="text-nowrap">3. rainy</p>
              <p className="text-nowrap">4. sunny</p>
              <p className="text-nowrap">5. cloudly</p>
            </div>
          </Key>
          <Exercise>Exercise 4</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">2. It&apos;s windly</p>
              <p className="text-nowrap">
                3. No, It&apos;s not snowy. It&apos;s stormy.
              </p>
              <p className="text-nowrap">
                4. No, It&apos;s not windly. It&apos;s cloudly.
              </p>
              <p className="text-nowrap">
                5. No, It&apos;s not stormy. It&apos;s snowy
              </p>
            </div>
          </Key>
          <Exercise>Exercise 5</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">1. big</p>
              <p className="text-nowrap">2. clean</p>
              <p className="text-nowrap">3. beautiful</p>
              <p className="text-nowrap">4. small, quiet</p>
              <p className="text-nowrap">5. busy, noisy</p>
            </div>
          </Key>
          <Exercise>Exercise 6</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">1. e</p>
              <p className="text-nowrap">2. c</p>
              <p className="text-nowrap">3. b</p>
              <p className="text-nowrap">4. a</p>
              <p className="text-nowrap">5. d</p>
            </div>
          </Key>
        </div>
        <div id="lesson-4" className="w-full">
          <Lesson>Lesson 4 : Let&apos;s send a postcard!</Lesson>
          <Skill>Writing</Skill>
          <Exercise>Exercise 1</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">1. c</p>
              <p className="text-nowrap">2. d</p>
              <p className="text-nowrap">3. e</p>
              <p className="text-nowrap">4. a</p>
              <p className="text-nowrap">5. b</p>
            </div>
          </Key>
          <Exercise>Exercise 3</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">1. c</p>
              <p className="text-nowrap">2. d</p>
              <p className="text-nowrap">3. e</p>
              <p className="text-nowrap">4. a</p>
              <p className="text-nowrap">5. b</p>
            </div>
          </Key>{" "}
          <Exercise>Exercise 4</Exercise>
          <Key>
            <div className="flex gap-5 flex-wrap">
              <p className="text-nowrap">1. Hi Myat Mon,</p>
              <p className="text-nowrap">2. a wonderful holiday</p>
              <p className="text-nowrap">3. It is sunny.</p>
              <p className="text-nowrap">4. See you on Monday!</p>
              <p className="text-nowrap">5. Kay Kay</p>
            </div>
          </Key>
        </div>
      </div>
      <RightAppSidebar items={items} />
    </SidebarProvider>
  );
}
