import { Metadata } from "next";
export const metadata: Metadata = {
  title: "ဒွါဒသမတန်း မြန်မာစာ မိတ်ဆက်ခြင်း",
  description: "Generated by create next app",
};
export default function Page() {
  return <div>မြန်မာစာ မိတ်ဆက်ခြင်း</div>;
}
