import {
  Section,
  SubSection,
  Title,
} from "@/components/courses/grade-12/myanmar/myanmar";
import { Card } from "@/components/ui/card";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "ဒွါဒသမတန်း မြန်မာစာ မိတ်ဆက်ခြင်း",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div className="w-full">
      <h1 className="flex text-3xl md:text-4xl font-bold w-full py-3 justify-center">
        မာတိကာ
      </h1>
      <Card className="mb-3 px-3">
        <Section>
          <h1>အပိုင်း - ၁</h1>
          <h2>အပြောသင်ခန်းစာ</h2>
        </Section>
        <SubSection>
          <h3 className="text-nowrap">အခန်း - ၁။</h3>
          <h3>စကားပြောရာတွင်ပါဝင်သောမွမ်းမံသံများ</h3>
        </SubSection>
        <Title>
          <h4>၁။</h4>
          <h4>အသံအနိမ့်အမြင့်သဘောတရား</h4>
        </Title>
        <Title>
          <h4>၂။</h4>
          <h4>အသံအလေးအပေါ့သဘောတရား</h4>
        </Title>
        <Title>
          <h4>၃။</h4>
          <h4>အသံအနှေးအမြန်သဘောတရား</h4>
        </Title>
        <SubSection>
          <h3 className="text-nowrap">အခန်း - ၂။</h3>
          <h3>အပြောအဆိုဆိုင်ရာနည်းလမ်းများ</h3>
        </SubSection>
        <Title>
          <h4>၁။</h4>
          <h4>ထိထိရောက်ရောက်စကားပြောဆိုခြင်း</h4>
        </Title>
        <Title>
          <h4>၂။</h4>
          <h4>စကားပြောကောင်းဖြစ်ရန်နည်းတို</h4>
        </Title>
        <SubSection>
          <h3 className="text-nowrap">အခန်း - ၃။</h3>
          <h3>အပြောအဆိုဆိုင်ရာပရိယာယ်များ</h3>
        </SubSection>
        <Title>
          <h4>၁။</h4>
          <h4>စကားပြောခြင်းဆိုင်ရာနည်းပရိယာယ်များ</h4>
        </Title>
        <Title>
          <h4>၂။</h4>
          <h4>ယဉ်ကျေးချေငံမှုဆိုင်ရာလမ်းညွှန်များ</h4>
        </Title>
      </Card>
      <Card className="mb-3 px-3">
        <Section>
          <h1>အပိုင်း - ၂</h1>
          <h2>အဖတ်အရွတ်သင်ခန်းစာ</h2>
        </Section>
        <SubSection>
          <h3 className="text-nowrap">အခန်း - ၁</h3>
          <h3>မြန်မာစကားပြေရွေးချယ်ချက်</h3>
        </SubSection>
        <Title>
          <h4>၁။</h4>
          <h4>ညောင်ရမ်းကြီးသမီး</h4>
        </Title>
        <Title>
          <h4>၂။</h4>
          <h4>သစ္စာနှင့်ပညာ</h4>
        </Title>
        <Title>
          <h4>၃။</h4>
          <h4>ခေတ်</h4>
        </Title>
        <Title>
          <h4>၄။</h4>
          <h4>မလုပ်မစား</h4>
        </Title>
        <Title>
          <h4>၅။</h4>
          <h4>စားဘူးတောင်း</h4>
        </Title>
        <Title>
          <h4>၆။</h4>
          <h4>ဦးဖေမောင်တင်</h4>
        </Title>
        <Title>
          <h4>၇။</h4>
          <h4>အဖြူနှင့်အနက်</h4>
        </Title>
        <Title>
          <h4>၈။</h4>
          <h4>စိတ်ဓာတ်ရင်ကျက်တည်ငြိမ်ခြင်း</h4>
        </Title>
        <SubSection>
          <h3 className="text-nowrap">အခန်း - ၂။</h3>
          <h3>မြန်မာကဗျာရွေးချယ်ချက်</h3>
        </SubSection>
        <Title>
          <h4>၁။</h4>
          <h4>ပေါ်နွေလလျှင်</h4>
        </Title>
        <Title>
          <h4>၂။</h4>
          <h4>ငါ့ကိုလွယ် အမယ်ကြီးနှင့်</h4>
        </Title>
        <Title>
          <h4>၃။</h4>
          <h4>ဩဝါဒထူးပျို့</h4>
        </Title>
        <Title>
          <h4>၄။</h4>
          <h4>ပေါင်းရှစ်ယောက် ကောက်စိုက်သူ</h4>
        </Title>
        <Title>
          <h4>၅။</h4>
          <h4>အညာမင်္ဂလာဆောင်</h4>
        </Title>
        <Title>
          <h4>၆။</h4>
          <h4>ကမ္ဗောဇသို့</h4>
        </Title>
        <Title>
          <h4>၇။</h4>
          <h4>လက်ဖက်ရည်ကြမ်းဝိုင်း</h4>
        </Title>
        <Title>
          <h4>၈။</h4>
          <h4>ပဒေသာလက်ရာ</h4>
        </Title>

        <SubSection>
          <h3 className="text-nowrap">အခန်း - ၃။</h3>
          <h3>အပြောအဆိုဆိုင်ရာပရိယာယ်များ</h3>
        </SubSection>
        <Title>
          <h4>၁။</h4>
          <h4>ရေသည်ပြဇာတ်</h4>
        </Title>
      </Card>
      <Card className="mb-3 px-3">
        <Section>
          <h1>အပိုင်း - ၃</h1>
          <h2>အရေးသင်ခန်းစာ</h2>
        </Section>
        <SubSection>
          <h3 className="text-nowrap">အခန်း - ၁။</h3>
          <h3>စာရေးသားရန်အကြောင်းအရာရွေးချယ်မှု</h3>
        </SubSection>
        <Title>
          <h4>၁။</h4>
          <h4>အကြောင်းအရာရွေးချယ်မှု</h4>
        </Title>
        <Title>
          <h4>၂။</h4>
          <h4>အကြောင်းအရာ၏ နယ်နိမိတ်ကန့်သတ်မှု</h4>
        </Title>
        <SubSection>
          <h3 className="text-nowrap">အခန်း - ၂။</h3>
          <h3>စာရေးသားရန် အကြောင်းအရာစီစဉ်ဖွဲ့စည်းခြင်း</h3>
        </SubSection>
        <Title>
          <h4>၁။</h4>
          <h4>အချက်အလက်စီစဉ်မှု</h4>
        </Title>
        <Title>
          <h4>၂။</h4>
          <h4>အစီအစဉ်ကောင်း၏ သဘောလက္ခဏာသုံးရပ်</h4>
        </Title>
        <SubSection>
          <h3 className="text-nowrap">အခန်း - ၃။</h3>
          <h3>ရေးဟန်အမျိုးမျိုးကို အသုံးပြုခြင်း</h3>
        </SubSection>
        <Title>
          <h4>၁။</h4>
          <h4>ရေးဟန်၏ သွင်ပြင်သုံးရပ်</h4>
        </Title>
        <Title>
          <h4>၂။</h4>
          <h4>စကားပြေရေးဟန်ကောင်း၏ အခြေခံလက္ခဏာများ</h4>
        </Title>
      </Card>
    </div>
  );
}
