import {
  TableBody,
  TableData,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/layouts/table";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 7 English လပိုင်းမာတိကာ",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <table className="table-auto table border-2 w-full text-sm md:text-base">
      <TableHeader>
        <TableRow>
          <TableHead>
            <p>သီ</p>
            <p>တင်း</p>
            <p>ပတ်</p>
          </TableHead>
          <TableHead>
            <p>သင်</p>
            <p>ချိန်</p>
            <p>ပေါင်း</p>
          </TableHead>
          <TableHead>
            <p>အခန်း</p>
            <p>(နယ်ပယ်)</p>
          </TableHead>
          <TableHead>
            <p>သင်ခန်းစာခေါင်းစဉ်</p>
            <p>(နယ်ပယ်ခွဲ)</p>
          </TableHead>
          <TableHead>အဓိကအကြောင်းအရာ/ ခေါင်းစဉ်ခွဲများ</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow>
          <TableData rowSpan={3}>၁</TableData>
          <TableData rowSpan={3}>၁</TableData>
          <TableData rowSpan={24}>အခန်း(၁) ရေးဆွဲခြင်း</TableData>
          <TableData rowSpan={3} align="left">
            (၁-၁) အလင်း၊ အမှောင်၊ ရောင်ပြန်နှင့်အရိပ်
          </TableData>
          <TableData align="left">
            (၁-၁-၁) အလင်း၊ အမှောင်၊ ရောင်ပြန်နှင့် အရိပ်တို့ဖြစ်ပေါ်ပုံ
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၁-၁-၂) ထုထည်များအပါ် အလင်းကျရောက်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၁-၃) ရေးဆွဲခြင်း အဆင့်ဆင့်</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={3}>၂</TableData>
          <TableData rowSpan={3}>၁</TableData>
          <TableData rowSpan={3} align="left">
            (၁-၂) ပျေက်ကွယ်စက် ၂ စက်ပါ နီးဝေးမြင် ပုံမှန်စနစ်ဖြင့် ရေးဆွဲခြင်း
          </TableData>
          <TableData align="left">
            (၁-၂-၁) မိုးကုပ်စက်ဝိုင်းမျဉ်းပေါ်တွင် ပျောက်ကွယ်စက် ၂စက်တည်ရှိခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၁-၂-၂) ပျောက်ကွယ်စက် ၂စက်ဖြင့် အဆင့်ဆင့်ရေးဆွဲခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၂-၃) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={4}>၃</TableData>
          <TableData rowSpan={4}>၁</TableData>
          <TableData rowSpan={4} align="left">
            (၁-၃) အလင်းကြောင့်ဖြစ်ပေါ်သော အသားသဘော
          </TableData>
          <TableData align="left">
            (၁-၃-၁) အလင်းကြောင့်ဖြစ်ပေါ်သော အသားသဘောသုံးမျိုး
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၁-၃-၂) အလင်းကြောင့်ဖြစ်ပေါ်သော အသားသဘောသုံးမျိုးကို လေ့လာခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၃-၃) နမူနာလက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၃-၄) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={4}>၄</TableData>
          <TableData rowSpan={4}>၁</TableData>
          <TableData rowSpan={4} align="left">
            (၁-၄) အလေးချိန်နှင့် ဟန်ချက်ညီမျှမှု
          </TableData>
          <TableData align="left">(၁-၄-၁) အလေးချိန်</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၄-၂) ဟန်ချက်ညီမျှမှု</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၄-၃) လက်တွေ့ရေးဆွဲခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၄-၄) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={4}>၅</TableData>
          <TableData rowSpan={4}>၁</TableData>
          <TableData rowSpan={4} align="left">
            (၁-၅) လူမျက်နှာပုံရေးဆွဲခြင်း
          </TableData>
          <TableData align="left">
            (၁-၅-၁) ဘဲဥပုံဖြင့် စတင်တည်ဆောက်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၁-၅-၂) ငြမ်းမျဉ်း(Skatch Line) များရေးဆွဲခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၁-၅-၃) ကျန်သောအစိတ်အပိုင်းများရေးဆွဲခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၅-၄) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={3}>၆</TableData>
          <TableData rowSpan={3}>၁</TableData>
          <TableData rowSpan={3} align="left">
            (၁-၆) လူပ်ငန်းလုပ်ချက်
          </TableData>
          <TableData align="left">(၁-၆-၁) လုပ်ငန်းလုပ်ချက်၏သဘောသဘာဝ</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၆-၂) နမူနာလက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၆-၃) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={3}>၇</TableData>
          <TableData rowSpan={3}>၁</TableData>
          <TableData rowSpan={3} align="left">
            (၁-၇) ခဲဖြင့် ပုံဆွဲလက်ရာတစ်ခု ဖန်တီးခြင်း
          </TableData>
          <TableData align="left">
            (၁-၇-၁) ပန်းချီကားဖန်တီးရေးဆွဲခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၇-၂) နမူနာလက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၁-၇-၃) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData>၈</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>အခန်း (၁) ကို ပြန်လည်သုံးသပ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData>၉</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>အခန်းဆုံးစာမေးပွဲ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={5}>၁၀</TableData>
          <TableData rowSpan={5}>၁</TableData>
          <TableData rowSpan={14}>အခန်း(၂) ဆေးခြယ်ခြင်း</TableData>
          <TableData rowSpan={5} align="left">
            (၂-၁) အရောင်များကို လေ့လာခြင်း
          </TableData>
          <TableData align="left">(၂-၁-၁) မူလအရောင်</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၂-၁-၂) ဒုတိယအရောင်</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၂-၁-၃) တတိယအရောင်</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၂-၁-၄) လက်တွေ့ရေးဆွဲခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၂-၁-၅) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={3}>၁၁</TableData>
          <TableData rowSpan={3}>၁</TableData>
          <TableData rowSpan={3} align="left">
            (၂-၂) ဆန့်ကျင်ဘက်အရောင်များ
          </TableData>
          <TableData align="left">
            (၂-၂-၁) အရောင်စက်ဝိုင်းအသုံပြု၍ ဆန့်ကျင်ဘက်အရောင်များကိုလေ့လာခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၂-၂-၂) လက်တွေ့ဆေးခြယ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၂-၂-၃) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={3}>၁၂</TableData>
          <TableData rowSpan={3}>၁</TableData>
          <TableData rowSpan={3} align="left">
            (၂-၃) မိတ်ဘက်အရောင်များ
          </TableData>
          <TableData align="left">
            (၂-၃-၁) အရောင်စက်ဝိုင်းအသုံပြု၍ မိတ်ဖက်အရောင်များကိုလေ့လာခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၂-၃-၂) လက်တွေ့ရေးဆွဲဆေးခြယ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၂-၃-၃) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={3}>၁၃</TableData>
          <TableData rowSpan={3}>၁</TableData>
          <TableData rowSpan={3} align="left">
            (၂-၄) အရောင်များဖြင့် ပန်းချီကားဖန်တီးခြင်း
          </TableData>
          <TableData align="left">
            (၂-၄-၁) ပန်းချီကား ဖန်တီးရေးခြယ်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၂-၄-၂) နမူနာလက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၂-၄-၃) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၄</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>အရန်စာသင်ချိန်</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၅</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>
            အခန်း (၁)၊ အခန်း (၂) ကိုပြန်လည်သုံးသပ်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={2}>၁၆</TableData>
          <TableData rowSpan={2}>၁</TableData>
          <TableData rowSpan={26}>အခန်း(၃) လက်မှုပညာ</TableData>
          <TableData rowSpan={2} align="left">
            (၃-၁) စက္ကူဖြင့် ခေါက်စက် ပုံဖော်ခြင်း
          </TableData>
          <TableData align="left">(၃-၁-၁) ငါးရုပ်ပုံဖော်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၁-၂) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={5}>၁၇</TableData>
          <TableData rowSpan={5}>၁</TableData>
          <TableData rowSpan={5} align="left">
            (၃-၂) စွန့်ပစ်ပစ္စည်းများဖြင့် အနုပညာလုပ်ဆောင်မှု (Art Work)
            တစ်ခုဖန်တီးခြင်း
          </TableData>
          <TableData align="left">(၃-၂-၁) ပုံကြမ်းလျာထားခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၂-၂) နေရာချခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၂-၃) ကော်ဖြင့်ကပ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၂-၄) အချောသပ်ပြုလုပ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၂-၅) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={4}>၁၈</TableData>
          <TableData rowSpan={4}>၁</TableData>
          <TableData rowSpan={4} align="left">
            (၃-၃) ရိုးရာအိမ်တစ်လုံး တည်ဆောက်ခြင်း
          </TableData>
          <TableData align="left">(၃-၃-၁) ပုံကြမ်းရေးဆွဲခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၃-၃-၂) အအေးပိုက်ချောင်းများအား ဖြတ်တောက်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၃-၃-၃) အစိတ်အပိုင်းတစ်ခုစီအလိုက်တွယ်စပ်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၃-၄) အချောသပ်ပြုလုပ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={6}>၁၉</TableData>
          <TableData rowSpan={6}>၁</TableData>
          <TableData rowSpan={6} align="left">
            (၃-၄) ရွှံ့ဖြင့် ကနုတ်ပန်းများ ပုံဖော်ခြင်း
          </TableData>
          <TableData align="left">
            (၃-၄-၁) စက္ကူပေါ်တွင် ပုံကြမ်းရေးခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၄-၂) ရွှံ့ပြားပြုလုပ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၃-၄-၃) ရွှံ့ပေါ်တွင် ပုံကြမ်းလျာထားခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၄-၄) ဖြတ်တောက်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၄-၅) အချောသပ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၄-၆) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={4}>၂၀</TableData>
          <TableData rowSpan={4}>၁</TableData>
          <TableData rowSpan={4} align="left">
            (၃-၅) အချိုရည်ဘူးခွံကို ပြည်လည်အသုံးချခြင်း
          </TableData>
          <TableData align="left">
            (၃-၅-၁) ဘူခွံပေါ်တွင် မျဉ်းများဆွဲခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၅-၂) မျဉ်းအတိုင်းဖောက်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၅-၃) ဆေးရောင်ခြယ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၃-၅-၄) အပင်များထည့်၍ စိုက်ပျိုးခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={5}>၂၁</TableData>
          <TableData rowSpan={5}>၁</TableData>
          <TableData rowSpan={5} align="left">
            (၃-၆) အုပ်စုလိုက်အနုပညာလုပ်ဆောင်မှု (Art Work) တစ်ခု ဖန်တီးခြင်း
          </TableData>
          <TableData align="left">(၃-၆-၁) တိုင်းတာမှတ်သားခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၆-၂) ဖြတ်တောက်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၆-၃) ကော်သုတ်ကပ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၆-၄) အံများပြုလုပ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၆-၅) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၂</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>စာမေးပွဲအတွက်ကြိုတင်ပြင်ဆင်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၃</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>ပထမနှစ် ဆုံးစာမေးပွဲ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={4}>၂၄</TableData>
          <TableData rowSpan={4}>၁</TableData>
          <TableData rowSpan={4}> </TableData>
          <TableData rowSpan={4} align="left">
            (၃-၇) အုပ်စုလိုက် ဒီဇိုင်းပြုလုပ်ဓာတ်ပုံရိုက်ခြင်း Photo Booth တစ်ခု
            ပြုလုပ်ခြင်း
          </TableData>
          <TableData align="left">(၃-၇-၁) ပုံကြမ်းလျာထားခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၇-၂) ဆေးခြယ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၇-၃) ဖြတ်တောက်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၇-၄) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={5}>၂၅</TableData>
          <TableData rowSpan={5}>၁</TableData>
          <TableData rowSpan={5}> </TableData>
          <TableData rowSpan={5} align="left">
            (၃-၈) အတန်းတွင် သစ်ပင်တစ်ပင် ဖန်တီးခြင်း
          </TableData>
          <TableData align="left">(၃-၈-၁) သစ်ပင်တွင် စက္ကူကပ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၈-၂) အရောင်ခြယ်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၈-၃) သစ်ရွက်ပေါ်တွင် စာရေးခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၃-၈-၄) သစ်ရွက်များကို သစ်ပင်တွင်ချိတ်ဆွဲခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">(၃-၈-၅) လေ့ကျင့်လက်ရာများ</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={2}>၂၆</TableData>
          <TableData rowSpan={2}>၁</TableData>
          <TableData rowSpan={3}>အခန်း(၄) ရသခံစား တန်ဖိုးထားမှု</TableData>
          <TableData rowSpan={2} align="left">
            (၄-၁) အင်းဝခေတ်၊ ညောင်ရမ်းခေတ် ပန်းချီအနုပညာလက်ရာများ
          </TableData>
          <TableData align="left">
            (၄-၁-၁) အင်းဝခေတ် ပန်းချီအနုပညာလက်ရာများ
          </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left">
            (၄-၁-၂) ညောင်ရမ်းခေတ် ပန်းချီအနုပညာလက်ရာများ
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၇</TableData>
          <TableData>၁</TableData>
          <TableData align="left">
            (၄-၂) ၂၀ရာစုအစောပိုင်း မြန်မာ့ပန်းချီသမိုင်းကြောင်းကို လေ့လာခြင်း
          </TableData>
          <TableData align="left">- မြန်မာ့ပန်းချီသမိုင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၈</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2} align="left">
            အခန်း(၃) ကိုပြန်လည်သုံးသပ်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၉</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2} align="left">
            အခန်း(၄) ကိုပြန်လည်သုံးသပ်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၀</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2} align="left">
            အခန်း(၁) ကိုပြန်လည်သုံးသပ်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၁</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2} align="left">
            အခန်း(၂) ကိုပြန်လည်သုံးသပ်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၂</TableData>
          <TableData> </TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>အခန်းဆုံးစာမေးပွဲ</TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၃</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2} align="left">
            အခန်း(၁) ၊ အခန်း(၂) ကိုပြန်လည်သုံးသပ်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၄</TableData>
          <TableData>၁</TableData>
          <TableData> </TableData>
          <TableData colSpan={2} align="left">
            အခန်း(၃) ၊ အခန်း(၄) ကိုပြန်လည်သုံးသပ်ခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၅</TableData>
          <TableData> </TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>စာမေးပွဲအတွက်ကြိုတင်ပြင်ဆင်ခြင်း</TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၆</TableData>
          <TableData> </TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>နှစ်ဆုံးစာမေးပွဲ</TableData>
        </TableRow>
      </TableBody>
    </table>
  );
}
