import {
  PoemItem,
  Poems,
  PoemTitle,
} from "@/components/courses/grade-12/english/english";
import poems from "@/datas/grade-12/english/poems/peoms.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <Poems>
      <PoemTitle>{poems.thequietlife.title}</PoemTitle>

      {poems.thequietlife.contents.map((item, index) => {
        return (
          <div
            key={index}
            className="w-full flex justify-center flex-col items-center"
          >
            {item.stanza.map((line, index) => (
              <PoemItem key={index}>{line}</PoemItem>
            ))}
            <div>{item.paraphrase}</div>
          </div>
        );
      })}
    </Poems>
  );
}
