import {
  TableBody,
  TableData,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/layouts/table";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 7 English လပိုင်းမာတိကာ",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <table className="table-auto table border-2 w-full text-sm md:text-base">
      <TableHeader>
        <TableRow>
          <TableHead>Unit</TableHead>
          <TableHead>Topic</TableHead>
          <TableHead>Period</TableHead>
          <TableHead>Schedule</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {/* Unit 1 */}
        <TableRow>
          <TableData>1</TableData>
          <TableData align="left" className="pl-5">
            Family, Friends and I
          </TableData>
          <TableData>8</TableData>
          <TableData rowSpan={4}>June and July</TableData>
        </TableRow>
        {/* Unit 2 */}
        <TableRow>
          <TableData>2</TableData>
          <TableData align="left" className="pl-5">
            My favourite ...
          </TableData>
          <TableData>8</TableData>
        </TableRow>
        {/* Review 1 */}
        <TableRow>
          <TableData colSpan={2}>Review 1</TableData>
          <TableData>2</TableData>
        </TableRow>
        {/* Project 1 */}
        <TableRow>
          <TableData colSpan={2}>Priject 1 : My family tree</TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 3 */}
        <TableRow>
          <TableData>3</TableData>
          <TableData align="left" className="pl-5">
            My house and my pets
          </TableData>
          <TableData>8</TableData>
          <TableData rowSpan={3}>August and September</TableData>
        </TableRow>
        {/* Unit 4 */}
        <TableRow>
          <TableData>4</TableData>
          <TableData align="left" className="pl-5">
            Numbers and shapes
          </TableData>
          <TableData>8</TableData>
        </TableRow>
        {/* Review 2 */}
        <TableRow>
          <TableData colSpan={2}>Review 2</TableData>
          <TableData>2</TableData>
        </TableRow>
        {/* Project 2 */}
        <TableRow>
          <TableData colSpan={2}>Priject 2 : Things in my bedroom</TableData>
          <TableData>3</TableData>
          <TableData rowSpan={3}>September and October</TableData>
        </TableRow>
        {/* Unit 5 */}
        <TableRow>
          <TableData>5</TableData>
          <TableData align="left" className="pl-5">
            Things I do at home and at school
          </TableData>
          <TableData>8</TableData>
        </TableRow>
        {/* Unit 6 */}
        <TableRow>
          <TableData>6</TableData>
          <TableData align="left" className="pl-5">
            My day
          </TableData>
          <TableData>8</TableData>
        </TableRow>
        {/* Review 3 */}
        <TableRow>
          <TableData colSpan={2}>Review 3</TableData>
          <TableData>2</TableData>
          <TableData rowSpan={6}>
            <p>November</p>
            <p>December</p>
            <p>January</p>
          </TableData>
        </TableRow>
        {/* Project 3 */}
        <TableRow>
          <TableData colSpan={2}>
            Priject 3 : The daily activities of my friend
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 7 */}
        <TableRow>
          <TableData>7</TableData>
          <TableData align="left" className="pl-5">
            Things we do for fun
          </TableData>
          <TableData>8</TableData>
        </TableRow>
        {/* Unit 8 */}
        <TableRow>
          <TableData>8</TableData>
          <TableData align="left" className="pl-5">
            Around town
          </TableData>
          <TableData>8</TableData>
        </TableRow>
        {/* Review 4 */}
        <TableRow>
          <TableData colSpan={2}>Review 4</TableData>
          <TableData>2</TableData>
        </TableRow>
        {/* Project 4 */}
        <TableRow>
          <TableData colSpan={2}>Priject 4 : My town</TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Reserved */}
        <TableRow>
          <TableData colSpan={2}>Reserved</TableData>
          <TableData>24</TableData>
          <TableData>January and February</TableData>
        </TableRow>
        {/* Total */}
        <TableRow>
          <TableData colSpan={2}>Total</TableData>
          <TableData>108</TableData>
        </TableRow>
      </TableBody>
    </table>
  );
}
