"use client";
import type { Metadata } from "next";
import { categories } from "@/datas/grade-10/chemistry/categories.json";
import { steams1, steams2 } from "@/datas/high/subjects.json";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import {
  AppSidebar,
  AppSidebarNav,
  AppContent,
} from "@/components/app-sidebar";
import { useSearchParams } from "next/navigation";
import { useGradeTypeStore } from "@/store/useGradeTypeStore";

// export const metadata: Metadata = {
//   title: "Grade 12 ",
//   description: "Generated by create next app",
// };

export default function Grade12Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { gradeType } = useGradeTypeStore();
  return (
    <div>
      <SidebarProvider>
        <AppSidebar
          data={categories}
          teams={gradeType === "steams2" ? steams2 : steams1}
          activeTeam={steams1.subjects[3]}
        />
        <SidebarInset>
          <AppSidebarNav />
          <AppContent>{children}</AppContent>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
}
