import PassQuestion from "@/components/courses/grade-12/biology/pass-questions/pass-question";
import question1 from "@/datas/grade-12/biology/pass-questions/2024/question1.json";
import question2 from "@/datas/grade-12/biology/pass-questions/2024/question2.json";
import question3 from "@/datas/grade-12/biology/pass-questions/2024/question3.json";
import question4 from "@/datas/grade-12/biology/pass-questions/2024/question4.json";
import question5 from "@/datas/grade-12/biology/pass-questions/2024/question5.json";
import question6 from "@/datas/grade-12/english/pass-questions/2024/question6.json";
import question7a from "@/datas/grade-12/english/pass-questions/2024/question7a.json";
import question7b from "@/datas/grade-12/english/pass-questions/2024/question7b.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "ဒွါဒသမတန်း အင်္ဂလိပ်စာ ၂၀၂၄ မေးခွန်း(၁)",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div>
      <PassQuestion
        year={2024}
        question1={question1.set1}
        question2={question2.set1}
        question3={question3.set1}
        question4={question4.set1}
        question5={question5.set1}
      />
    </div>
  );
}
