import {
  TableBody,
  TableData,
  TableHead,
  TableRow,
} from "@/components/layouts/table";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 6 Myanmar",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div className="w-full">
      <h1 className="text-center py-3 text-3xl font-bold">
        သတ္တမတန်း အင်္ဂလိပ်စာ မိတ်ဆက်ခြင်း
      </h1>
      <h1>Contents</h1>
      <table className="table-auto table border-0 w-full text-sm md:text-base">
        <TableBody>
          <TableRow className="bg-yellow-600 dark:bg-yellow-800 pl-3-800 border-0">
            <TableHead align="left" className="border-0 pl-3">
              Unit
            </TableHead>
            <TableHead className="border-0">Title</TableHead>
          </TableRow>
          {/* Unit 1 */}
          <TableRow className="bg-blue-600 dark:bg-blue-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Unit 1
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData className="border-0 pl-3" align="left">
              My favourite singer
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="border-0 pl-3">
              Life as an artiste
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="border-0 pl-3">
              Comparing people or TableHeadings
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="border-0 pl-3">
              A personal profile
            </TableData>
          </TableRow>
          {/* Unit 2 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 2
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Keeping good habits
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Getting rid of bad habits
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              What an annoying habit!
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              What do you usually do at weekends?
            </TableData>
          </TableRow>
          {/* Unit 3 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 3
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              At the clothes shop
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Accessories you usually do for
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              The mot expensive jeans
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A nice blue cotton T-shirt
            </TableData>
          </TableRow>
          {/* Review , Project and Poem (1 className="border-0") */}
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Review 1
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Project 1
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData align="left" className="pl-3 border-0">
              Poem 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              The Lazy Boy
            </TableData>
          </TableRow>
          {/* Unit 4 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 4
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Travel and transport
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A holiday in Mandalay
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Can you tell me about your holiday?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Going on a holiday
            </TableData>
          </TableRow>
          {/* Unit 5 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 5
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Sports and games
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Football
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              <p>Which sport and games do you prefer, indoor or outdoor?</p>
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Dos and Don’ts in sports and games
            </TableData>
          </TableRow>
          {/* Unit 6 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 6
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              To the pizza shop
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Amber: The Little Yellowish-brown Light
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Do you like living in the countryside?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              The best things about your town
            </TableData>
          </TableRow>
          {/* Review , Project and Poem (2 className="border-0") */}
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Review 2
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Project 2
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData align="left" className="pl-3 border-0">
              Poem 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              The Greendy Dog
            </TableData>
          </TableRow>
          {/* Unit 7 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 7
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A day in the life of a teacher
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Days and their names
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Do you help your parents?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Do you have a study timetable?
            </TableData>
          </TableRow>
          {/* Unit 8 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 8
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Little friends can be great friends
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Friends always help each other
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              What were you doing?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Once a upon a time ...
            </TableData>
          </TableRow>
          {/* Unit 9 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 9
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A special celebration for my birthday
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              An enjoyable visit
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Would you like to join us for dinner?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              An invitation
            </TableData>
          </TableRow>
          {/* Review , Project and Poem (3 className="border-0") */}
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Review 3
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Project 3
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData align="left" className="pl-3 border-0">
              Poem 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              The Sun
            </TableData>
          </TableRow>
          {/* Unit 10 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 10
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Let’s take part in the school concert!
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A trip to a World Heritage Site in Myanmar
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              She’s quite intelligent, but rather lazy
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              The school snack fair
            </TableData>
          </TableRow>
          {/* Unit 11 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 11
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A beautiful, sunny day
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Weather instruments
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              What will you do if ...?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Let’s write a weather forecast!
            </TableData>
          </TableRow>
          {/* Unit 12 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 12
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Seeing a doctor
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Staying healthy
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A word of advice
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              What should I do?
            </TableData>
          </TableRow>
          {/* Review , Project and Poem (4 className="border-0") */}
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Review 4
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Project 4
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData align="left" className="pl-3 border-0">
              Poem 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Thechers three
            </TableData>
          </TableRow>
        </TableBody>
      </table>
    </div>
  );
}
