import type { Metadata } from "next";
import subjects from "@/components/middle/subjects.json";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import {
  AppContent,
  AppSidebar,
  AppSidebarNav,
} from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Grade 6",
  description: "Generated by create next app",
};

const data = {
  user: {
    name: "shadcn",
    email: "m@example.com",
    avatar: "/avatars/shadcn.jpg",
  },
  navMain: [
    {
      title: "မိတ်ဆက်သင်ခန်းစာ",
      url: "/introduction",
    },
    {
      title: "လေ့ကျင့်ခန်းနှင့်အဖြေများ",
      url: "#",
      items: [
        {
          title: "Genesis",
          url: "#",
        },
        {
          title: "Explorer",
          url: "#",
        },
        {
          title: "Quantum",
          url: "#",
        },
      ],
    },
    {
      title: "၂၀၂၄ မေးခွန်းဟောင်းများ",
      url: "#",
      items: [
        {
          title: "မေးခွန်းဟောင်းများ (၁)",
          url: "",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၂)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၃)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၄)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၅)",
          url: "#",
        },
      ],
    },
    {
      title: "၂၀၂၅ မေးခွန်းဟောင်းများ",
      url: "#",
      items: [
        {
          title: "မေးခွန်းဟောင်းများ (၁)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၂)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၃)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၄)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၅)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၆)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၇)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၈)",
          url: "#",
        },
        {
          title: "မေးခွန်းဟောင်းများ (၉)",
          url: "#",
        },
      ],
    },
  ],
};

export default function Grade12Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <SidebarProvider>
        <AppSidebar
          data={data}
          teams={subjects}
          activeTeam={subjects.subjects[2]}
        />
        <SidebarInset>
          <AppSidebarNav />
          <AppContent>{children}</AppContent>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
}
