import { PassQuestions7 } from "@/components/grade-12/english/pass-questions/2025";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
export default function Page() {
  return <PassQuestions7 />;
}
