import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 7 English Intro",
  description: "Generated by create next app",
};
export default function Page() {
  return <div>Essay ရေးသားနည်း (၃)</div>;
}
