import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 7 English Intro",
  description: "Generated by create next app",
};
export default function Page() {
  return <div>စာရိတ္တနှင့် ပြည်သူ့နီတိ မိတ်ဆက်ခြင်း</div>;
}
