import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
export default function Intro() {
  return <div>မြန်မာစာ မိတ်ဆက်ခြင်း သင်ခန်းစာ</div>;
}
