import {
  PoemItem,
  Poems,
  PoemTitle,
} from "@/components/courses/grade-12/english/english";
import { RightAppSidebar } from "@/components/right-sidebar";
import { SidebarProvider } from "@/components/ui/right-sidebar";
import poems from "@/datas/grade-12/english/poems/peoms.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};

const items = [
  {
    url: "#thelibarary",
    lesson: "POEM 1",
    title: "The Libarary",
  },
  {
    url: "#thequietlife",
    lesson: "POEM 2",
    title: "The Quietlife",
  },
  {
    url: "#theroadnottaken",
    lesson: "POEM 3",
    title: "The Road Not Taken",
  },
  { url: "#windynights", lesson: "POEM 4", title: "Windy Nights" },
];
export default function Page() {
  return (
    <SidebarProvider>
      <div className="w-full">
        <Poems>
          <div id="thelibarary"></div>
          <PoemTitle>{poems.thelibrary.title}</PoemTitle>
          {poems.thelibrary.contents.map((item, index) => {
            return (
              <PoemItem key={index}>
                {item.stanza.map((line, index) => (
                  <PoemItem key={index}>{line}</PoemItem>
                ))}
                {/* <div>{item.paraphrase}</div> */}
              </PoemItem>
            );
          })}
        </Poems>
        <Poems>
          <div id="thequietlife"></div>
          <PoemTitle>{poems.thequietlife.title}</PoemTitle>
          {poems.thequietlife.contents.map((item, index) => {
            return (
              <PoemItem key={index}>
                {item.stanza.map((line, index) => (
                  <PoemItem key={index}>{line}</PoemItem>
                ))}
                {/* <div>{item.paraphrase}</div> */}
              </PoemItem>
            );
          })}
        </Poems>
        <Poems>
          <div id="theroadnottaken"></div>
          <PoemTitle>{poems.theroadnottaken.title}</PoemTitle>
          {poems.theroadnottaken.contents.map((item, index) => {
            return (
              <PoemItem key={index}>
                {item.stanza.map((line, index) => (
                  <PoemItem key={index}>{line}</PoemItem>
                ))}
                {/* <div>{item.paraphrase}</div> */}
              </PoemItem>
            );
          })}
        </Poems>
        <Poems>
          <div id="windynights"></div>
          <PoemTitle>{poems.windynights.title}</PoemTitle>
          {poems.windynights.contents.map((item, index) => {
            return (
              <PoemItem key={index}>
                {item.stanza.map((line, index) => (
                  <PoemItem key={index}>{line}</PoemItem>
                ))}
                {/* <div>{item.paraphrase}</div> */}
              </PoemItem>
            );
          })}
        </Poems>
      </div>
      <RightAppSidebar items={items} />
    </SidebarProvider>
  );
}
