import type { Metadata } from "next";
import gradeType from "@/data/gradeType.json";
import { data } from "@/components/grade-12/english/data";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import {
  AppSidebar,
  AppSidebarNav,
  AppContent,
} from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Grade 12 ",
  description: "Generated by create next app",
};

export default function Grade12Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar
        data={data}
        teams={gradeType.stams}
        activeTeam={gradeType.stams.subjects[1]}
      />
      <SidebarInset>
        <AppSidebarNav />
        <AppContent>{children}</AppContent>
      </SidebarInset>
    </SidebarProvider>
  );
}
