import {
  TableBody,
  TableData,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/layouts/year-plan";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 7 English လပိုင်းမာတိကာ",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <table className="table-auto table border-2 w-full text-sm md:text-base">
      <TableHeader>
        <TableRow>
          <TableHead>သတင်းပတ်</TableHead>
          <TableHead>အချိန်</TableHead>
          <TableHead>အခန်းခေါင်းစဉ်</TableHead>
          <TableHead>သင်ခန်းစာခေါင်းစဉ်</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow>
          <TableData>၁</TableData>
          <TableData>၂</TableData>
          <TableData rowSpan={7}>ကိုယ်ခန္ဓာကြံ့ခိုင်ရေး</TableData>
          <TableData rowSpan={4}>
            ကျန်းမာကြံ့ခိုင်မှုနှင့်ဆက်နွယ်သောလေ့ကျင့်ခန်းများ
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၂</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၃</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData rowSpan={2}>၄</TableData>
          <TableData>၁</TableData>
        </TableRow>
        {/* Unit 2 */}
        <TableRow>
          <TableData>၁</TableData>
          <TableData rowSpan={3}>
            အားကစားနည်းများအလိုက် ကျွမ်းကျင်မှုရရှိစေသည့် လေ့ကျင့်ခန်းများ
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၅</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၆</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၇</TableData>
          <TableData>၂</TableData>
          <TableData rowSpan={8}>အားကစားနည်းများ</TableData>
          <TableData>
            ကာယလှုပ်ရှားမှုနှင့်အားကစားလုပ်ဆောင်ရာတွင် အန္တာရာယ်ကင်းရှင်းရေး
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၈</TableData>
          <TableData>၂</TableData>
          <TableData>ကာယပညာသင်ကြားရေး၏စီမံခန့်ခွဲမှု</TableData>
        </TableRow>
        <TableRow>
          <TableData>၉</TableData>
          <TableData>၂</TableData>
          <TableData>တစ်ဦးချင်းကစားနည်း</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၀</TableData>
          <TableData>၂</TableData>
          <TableData rowSpan={5}>နှစ်ယောက်တွဲကစားနည်း</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၁</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၂</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၃</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၄</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၅</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>
            စာမေးပွဲအတွက်ကြိုတင်ပြင်ဆင်ခြင်း- ပြန်လှန်သင်ကြားခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၆</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>ပထမနှစ်ဝက်ဆုံးစာမေးပွဲ</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၇</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>ကျောင်းပိတ်ရက်</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၈</TableData>
          <TableData>၂</TableData>
          <TableData rowSpan={10}> </TableData>
          <TableData rowSpan={10}>အုပ်စုလိုက်ကစားနည်း</TableData>
        </TableRow>
        <TableRow>
          <TableData>၁၉</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၀</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၁</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၂</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၃</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၄</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၅</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၆</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၇</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၈</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>
            စာမေးပွဲအတွက်ကြိုတင်ပြင်ဆင်ခြင်း - ပြန်လှန်သင်ကြားခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၂၉</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>ဒုတိယနှစ်ဝက်ဆုံးစာမေးပွဲ</TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၀</TableData>
          <TableData>၂</TableData>
          <TableData rowSpan={5}>
            အားကစားနှင့်ဆက်နွှယ်သော ကျန်းမားရေး အသိပညာများ
          </TableData>
          <TableData>ကျန်းမာရေးနှင့်အာဟာရ</TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၁</TableData>
          <TableData>၂</TableData>
          <TableData rowSpan={2}>
            ကျန်းမာရေးနှင့်ဆက်နွှယ်သော အပန်းဖြေကစားနည်းများ
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၂</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၃</TableData>
          <TableData>၂</TableData>
          <TableData rowSpan={2}>ကိုယ်ကာယကြံ့ခိုင်မှုအစီအစဉ်</TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၄</TableData>
          <TableData>၂</TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၅</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>
            စာမေးပွဲအတွက်ကြိုတင်ပြင်ဆင်ခြင်း - ပြန်လှန်သင်ကြားခြင်း
          </TableData>
        </TableRow>
        <TableRow>
          <TableData>၃၆</TableData>
          <TableData> </TableData>
          <TableData colSpan={2}>နှစ်ဆုံးစာမေးပွဲ</TableData>
        </TableRow>
      </TableBody>
    </table>
  );
}
