import PassQuestion from "@/components/courses/grade-12/english/pass-questions/pass-question";
import question1 from "@/datas/grade-12/english/pass-questions/2024/question1.json";
import question2 from "@/datas/grade-12/english/pass-questions/2024/question2.json";
import question3 from "@/datas/grade-12/english/pass-questions/2024/question3.json";
import question4a from "@/datas/grade-12/english/pass-questions/2024/question4a.json";
import question4b from "@/datas/grade-12/english/pass-questions/2024/question4b.json";
import question5 from "@/datas/grade-12/english/pass-questions/2024/question5.json";
import question6 from "@/datas/grade-12/english/pass-questions/2024/question6.json";
import question7a from "@/datas/grade-12/english/pass-questions/2024/question7a.json";
import question7b from "@/datas/grade-12/english/pass-questions/2024/question7b.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
export function Set1() {
  return (
    <div>
      <PassQuestion
        year={2024}
        question1={question1.set1}
        question2={question2.set1}
        question3={question3.set1}
        question4a={question4a.set1}
        question4b={question4b.set1}
        question5={question5.set1}
        question6={question6.set1}
        question7a={question7a.set1}
        question7b={question7b.set1}
      />
    </div>
  );
}
export function Set2() {
  return (
    <div>
      <PassQuestion
        year={2024}
        question1={question1.set2}
        question2={question2.set2}
        question3={question3.set2}
        question4a={question4a.set2}
        question4b={question4b.set2}
        question5={question5.set2}
        question6={question6.set2}
        question7a={question7a.set2}
        question7b={question7b.set2}
      />
    </div>
  );
}

export function Set3() {
  return (
    <div>
      <PassQuestion
        year={2024}
        question1={question1.set3}
        question2={question2.set3}
        question3={question3.set3}
        question4a={question4a.set3}
        question4b={question4b.set3}
        question5={question5.set3}
        question6={question6.set3}
        question7a={question7a.set3}
        question7b={question7b.set3}
      />
    </div>
  );
}
export function Set4() {
  return (
    <div>
      <PassQuestion
        year={2024}
        question1={question1.set4}
        question2={question2.set4}
        question3={question3.set4}
        question4a={question4a.set4}
        question4b={question4b.set4}
        question5={question5.set4}
        question6={question6.set4}
        question7a={question7a.set4}
        question7b={question7b.set4}
      />
    </div>
  );
}
