import PassQuestion from "@/components/courses/grade-12/chemistry/pass-questions/pass-question";
import question1 from "@/datas/grade-12/chemistry/pass-questions/2025/question1.json";
import question2 from "@/datas/grade-12/chemistry/pass-questions/2025/question2.json";
import question3 from "@/datas/grade-12/chemistry/pass-questions/2025/question3.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "ဒွါဒသမတန်း အင်္ဂလိပ်စာ ၂၀၂၄ မေးခွန်း(၁)",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div>
      <PassQuestion
        year="2025"
        question1={question1.set9}
        question2={question2.set9}
        question3={question3.set9}
      />
    </div>
  );
}
