import {
  Exercise,
  Lesson,
  Skill,
  Unit,
} from "@/components/courses/english/english";
import { AppContent, RightAppSidebar } from "@/components/right-sidebar";
import { SidebarProvider } from "@/components/ui/right-sidebar";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 6 English Text Keys Unit 1",
  description: "Generated by create next app",
};
const items = [
  {
    url: "#lesson-1",
    lesson: "Lesson 1",
    title: "Where shall we meet?",
  },
  {
    url: "#lesson-2",
    lesson: "Lesson 2",
    title: "Let’s s read a short note",
  },
  {
    url: "#lesson-3",
    lesson: "Lesson 3",
    title: "Where are you from?",
  },
  { url: "#lesson-4", lesson: "Lesson 4", title: "Filling in a form" },
];
export default function Page() {
  return (
    <SidebarProvider className="w-full">
      <div className="w-full">
        <div id="lesson-1" className="w-full min-h-screen">
          <Unit>Unit 5</Unit>
          <Lesson>Lesson 1 : Where shall we meet?</Lesson>
          <Skill>Listening</Skill>
          <Exercise>Exercise 2</Exercise>
          <div>Aung Aung, Su Hlaing, Yangon, Bye!,See You!</div>
        </div>
        <div id="lesson-2" className="w-full min-h-screen">
          <Lesson>Lesson 2 : Let’s read a short note</Lesson>
          <Skill>Reading</Skill>
          <Exercise>Exercise 1</Exercise>
        </div>
        <div id="lesson-3" className="w-full min-h-screen">
          <Lesson>Lesson 3 : Where are you from?</Lesson>
          <Skill>Vocabulary</Skill>
          <Exercise>Exercise 1</Exercise>
        </div>
        <div id="lesson-4" className="w-full min-h-screen">
          <Lesson>Lesson 4 : Filling in a form</Lesson>
          <Skill>Writing</Skill>
          <Exercise>Exercise 1</Exercise>
        </div>
      </div>
      <RightAppSidebar items={items} />
    </SidebarProvider>
  );
}
