import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Page - Alinn Education",
  description: "Generated by create next app",
};
export default function HomePage() {
  return <div></div>;
}
