import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Us - Alinn Education",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div className="w-full h-full px-5 py-5">
      <h3>Alinn Education</h3>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque non
        accusantium recusandae, veniam dicta porro enim velit quos voluptas quis
        at corporis! Dolore quod doloribus repellat, deserunt suscipit culpa
        incidunt.
      </p>
    </div>
  );
};

export default page;
