import {
  TableBody,
  TableData,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/middle/year-plan";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 7 English လပိုင်းမာတိကာ",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <table className="table-auto table border-2 w-full">
      <TableHeader>
        <TableRow>
          <TableHead>Unit</TableHead>
          <TableHead>Lesson</TableHead>
          <TableHead>Topic</TableHead>
          <TableHead>Period</TableHead>
          <TableHead>
            <p>Total</p>
            <p> Periods </p>
            <p>for each </p>
            <p>unit</p>
          </TableHead>
          <TableHead>Schedule</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {/* Unit 1 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 1</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            My favourite singer
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={7}>June</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Life as an artiste
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Comparing people or TableHeadings
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            A personal profile
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 2 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 2</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Keeping good habits
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Getting rid of bad habits
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            What an annoying habit!
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            What do you usually do at weekends?
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={8}>July</TableData>
        </TableRow>
        {/* Unit 3 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 3</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            At the clothes shop
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Accessories you usually do for
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            The mot expensive jeans
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            A nice blue cotton T-shirt
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Review , Project and Poem (1) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 1</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 1</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 1</TableData>
          <TableData align="left" className="pl-5">
            The Lazy Boy
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        {/* Unit 4 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 4</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Travel and transport
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={6}>August</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            A holiday in Mandalay
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Can you tell me about your holiday?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Going on a holiday
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 5 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 5</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Sports and games
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Football
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            <p>Which sport and games do you prefer,</p>
            <p>indoor or outdoor?</p>
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={7}>September</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Dos and Don'ts in sports and games
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 6 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 6</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            To the pizza shop
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Amber: The Little Yellowish-brown Light
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Do you like living in the countryside?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            The best things about your town
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Review , Project and Poem (2) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 2</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 2</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={6}>October</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 2</TableData>
          <TableData align="left" className="pl-5">
            The Greendy Dog
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        {/* Unit 7 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 7</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            A day in the life of a teacher
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Days and their names
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Do you help your parents?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Do you have a study timetable?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 8 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 8</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Little friends can be great friends
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={7}>November</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Friends always help each other
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            What were you doing?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Once a upon a time ...
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 9 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 9</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            A special celebration for my birthday
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            An enjoyable visit
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            Would you like to join us for dinner?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            An invitation
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={8}>December</TableData>
        </TableRow>
        {/* Review , Project and Poem (3) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 3</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 3</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 3</TableData>
          <TableData align="left" className="pl-5">
            The Sun
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        {/* Unit 10 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 10</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Let's take part in the school concert!
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            <p>A trip to a World Heritage Site in</p>
            <p>Myanmar</p>
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            She's quite intelligent, but rather lazy
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            The school snack fair
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 11 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 11</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            A beautiful, sunny day
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
          <TableData rowSpan={7}>January</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Weather instruments
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            What will you do if ...?
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            Let's write a weather forecast!
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        {/* Unit 12 */}
        <TableRow>
          <TableData rowSpan={4}>Unit 12</TableData>
          <TableData>Lesson 1</TableData>
          <TableData align="left" className="pl-5">
            Seeing a doctor
          </TableData>
          <TableData>4</TableData>
          <TableData rowSpan={4}>14</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 2</TableData>
          <TableData align="left" className="pl-5">
            Staying healthy
          </TableData>
          <TableData>4</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 3</TableData>
          <TableData align="left" className="pl-5">
            A word of advice
          </TableData>
          <TableData>3</TableData>
        </TableRow>
        <TableRow>
          <TableData>Lesson 4</TableData>
          <TableData align="left" className="pl-5">
            What should I do?
          </TableData>
          <TableData>3</TableData>
          <TableData rowSpan={4}>February</TableData>
        </TableRow>
        {/* Review , Project and Poem (4) */}
        <TableRow>
          <TableData rowSpan={3}>
            <p>Review,</p>
            <p>Project &</p>
            <p>Poem</p>
          </TableData>
          <TableData>Review 4</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
          <TableData rowSpan={3}>5</TableData>
        </TableRow>
        <TableRow>
          <TableData>Project 4</TableData>
          <TableData> </TableData>
          <TableData>2</TableData>
        </TableRow>
        <TableRow>
          <TableData>Poem 4</TableData>
          <TableData align="left" className="pl-5">
            Thecher three
          </TableData>
          <TableData>1</TableData>
        </TableRow>
        <TableRow>
          <TableData colSpan={2} rowSpan={3}>
            {" "}
          </TableData>
          <TableData align="left" className="pl-5">
            Total (Teaching periods)
          </TableData>
          <TableData> </TableData>
          <TableData>188</TableData>
          <TableData rowSpan={3}> </TableData>
        </TableRow>
        <TableRow>
          <TableData align="left" className="pl-5">
            Reserve(revision and exam)
          </TableData>
          <TableData> </TableData>
          <TableData>28</TableData>
        </TableRow>
        <TableRow>
          <TableData align="left" className="pl-5 font-bold">
            Total
          </TableData>
          <TableData> </TableData>
          <TableData className="font-bold">216</TableData>
        </TableRow>
      </TableBody>
    </table>
  );
}
