import type { Metadata } from "next";
import { stams } from "@/datas/high/subjects.json";
import { data } from "@/components/courses/grade-12/geography/data";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import {
  AppSidebar,
  AppSidebarNav,
  AppContent,
} from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Grade 12 ",
  description: "Generated by create next app",
};

export default function Grade12Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar data={data} teams={stams} activeTeam={stams.subjects[4]} />
      <SidebarInset>
        <AppSidebarNav />
        <AppContent>{children}</AppContent>
      </SidebarInset>
    </SidebarProvider>
  );
}
