import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 6 Myanmar",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div className="w-full">
      <h1 className="text-center py-3 text-3xl font-bold">
        ဆဋ္ဌမတန်း သိပ္ပံ မိတ်ဆက်ခြင်း
      </h1>
    </div>
  );
}
