import {
  TableBody,
  TableData,
  TableHead,
  TableRow,
} from "@/components/layouts/table";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 6 Myanmar",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div className="w-full">
      <h1 className="text-center py-3 text-3xl font-bold">
        ဆဋ္ဌမတန်း အင်္ဂလိပ်စာ မိတ်ဆက်ခြင်း
      </h1>
      <h1>Contents</h1>
      <table className="table-auto table border-0 w-full text-sm md:text-base">
        <TableBody>
          <TableRow className="bg-yellow-600 dark:bg-yellow-800 pl-3-800 border-0">
            <TableHead align="left" className="border-0 pl-3">
              Unit
            </TableHead>
            <TableHead className="border-0">Title</TableHead>
          </TableRow>
          {/* Unit 1 */}
          <TableRow className="bg-blue-600 dark:bg-blue-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Unit 1
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData className="border-0 pl-3" align="left">
              Greeting, introducing and leave-taking
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="border-0 pl-3">
              Greetings from postcards
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="border-0 pl-3">
              Greetings for special events
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="border-0 pl-3">
              Greetings from postcards
            </TableData>
          </TableRow>
          {/* Unit 2 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 2
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Tell me about you!
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Talking about families
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              My best friend
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Daily routine
            </TableData>
          </TableRow>
          {/* Unit 3 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 3
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Talking about your city
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              At the market
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              What is it?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              My favourite room
            </TableData>
          </TableRow>
          {/* Review , Project and Poem (1 className="border-0") */}
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Review 1
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Project 1
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData align="left" className="pl-3 border-0">
              Poem 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              The Owl
            </TableData>
          </TableRow>
          {/* Unit 4 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 4
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Talking about your family and free time
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A happy family
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Talking about habits and routines
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              What we like and dislike!
            </TableData>
          </TableRow>
          {/* Unit 5 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 5
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Where shall we meet?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Let’s read a short note!
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Where are you from?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Filling in a form
            </TableData>
          </TableRow>
          {/* Unit 6 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 6
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Let’s eat out!
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Do you eat healthy food?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              <p>What’s the difference: countable and uncountable?</p>
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Let’s go shopping!
            </TableData>
          </TableRow>
          {/* Review , Project and Poem (2 className="border-0") */}
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Review 2
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Project 2
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData align="left" className="pl-3 border-0">
              Poem 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Early to bed and early to rise
            </TableData>
          </TableRow>
          {/* Unit 7 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 7
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              What does he look like?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              What is she wearing?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Who is the tallest?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Find someone who ...
            </TableData>
          </TableRow>
          {/* Unit 8 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 8
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              How much is it?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Look at this leaflet!
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              How much do you want?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Happy birthday!
            </TableData>
          </TableRow>
          {/* Unit 9 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 9
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Requesting
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              My favourite possessions
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              This is mine!
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Does this pen belong to you?
            </TableData>
          </TableRow>
          {/* Review , Project and Poem (3 className="border-0") */}
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Review 3
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Project 3
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData align="left" className="pl-3 border-0">
              Poem 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              The rainbow
            </TableData>
          </TableRow>
          {/* Unit 10 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 10
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Sport is great!
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A myanmar lady sport star to admire
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              We are doing sports
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A sports star I like
            </TableData>
          </TableRow>
          {/* Unit 11 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 11
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              I love my school
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Our school keeps discipline
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Must or Can?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              A phone message
            </TableData>
          </TableRow>
          {/* Unit 12 */}
          <TableRow className="border-0">
            <TableData
              className="border-0 bg-blue-600 dark:bg-blue-900 pl-3"
              align="left"
              colSpan={2}
            >
              Unit 12
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 1
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Shapes
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 2
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              The Tin Man looking for a heart
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 3
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              What shape is it?
            </TableData>
          </TableRow>
          <TableRow className="border-0">
            <TableData align="left" className="border-0 pl-3 text-nowrap">
              Lesson 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              Can you describe it?
            </TableData>
          </TableRow>
          {/* Review , Project and Poem (4 className="border-0") */}
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Review 4
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData colSpan={2} align="left" className="pl-3 border-0">
              Project 4
            </TableData>
          </TableRow>
          <TableRow className="bg-pink-600 dark:bg-pink-800 border-0">
            <TableData align="left" className="pl-3 border-0">
              Poem 4
            </TableData>
            <TableData align="left" className="pl-3 border-0">
              The butterfly
            </TableData>
          </TableRow>
        </TableBody>
      </table>
    </div>
  );
}
