import PassQuestion from "@/components/courses/grade-12/english/pass-questions/pass-question";
import question1 from "@/datas/grade-12/english/pass-questions/2025/question1.json";
import question2 from "@/datas/grade-12/english/pass-questions/2025/question2.json";
import question3 from "@/datas/grade-12/english/pass-questions/2025/question3.json";
import question4a from "@/datas/grade-12/english/pass-questions/2025/question4a.json";
import question4b from "@/datas/grade-12/english/pass-questions/2025/question4b.json";
import question5 from "@/datas/grade-12/english/pass-questions/2025/question5.json";
import question6 from "@/datas/grade-12/english/pass-questions/2025/question6.json";
import question7a from "@/datas/grade-12/english/pass-questions/2025/question7a.json";
import question7b from "@/datas/grade-12/english/pass-questions/2025/question7b.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Grade 12 Myanmar Pass Questions(2024)-1",
  description: "Generated by create next app",
};
export default function Page() {
  return (
    <div>
      <PassQuestion
        year={2025}
        question1={question1.set2}
        question2={question2.set2}
        question3={question3.set2}
        question4a={question4a.set2}
        question4b={question4b.set2}
        question5={question5.set2}
        question6={question6.set2}
        question7a={question7a.set2}
        question7b={question7b.set2}
      />
    </div>
  );
}
