"use client";
import type { Metadata } from "next";
import { categories } from "@/datas/grade-12/biology/categories.json";
import { steams1 } from "@/datas/high/subjects.json";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import {
  AppSidebar,
  AppSidebarNav,
  AppContent,
} from "@/components/app-sidebar";
import { useEffect } from "react";
import { useGradeTypeStore } from "@/store/useGradeTypeStore";

// export const metadata: Metadata = {
//   title: "Grade 12 ",
//   description: "Generated by create next app",
// };

export default function Grade12Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { changeGradeType } = useGradeTypeStore();
  useEffect(() => {
    changeGradeType("steams1");
  }, []);
  return (
    <div>
      <SidebarProvider>
        <AppSidebar
          data={categories}
          teams={steams1}
          activeTeam={steams1.subjects[5]}
        />
        <SidebarInset>
          <AppSidebarNav />
          <AppContent>{children}</AppContent>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
}
