"use client";
import { logout, signInWithGoogle } from "@/db/authFunctions";
import { useAuth } from "@/db/useAuth";
// import { Metadata } from "next";
import React from "react";
// export const metadata: Metadata = {
//   title: "Teachers - Alinn Education",
//   description: "Generated by create next app",
// };
const Teachers = () => {
  const { user } = useAuth();
  return (
    <div>
      {user ? (
        <>
          <p>Welcome, {user.displayName}</p>
          <button onClick={logout}>Logout</button>
        </>
      ) : (
        <button onClick={signInWithGoogle}>Sign In wiht Google</button>
      )}
    </div>
  );
};

export default Teachers;
