import type { Metadata } from "next";
import subjects from "@/datas/middle/subjects.json";
import { categories } from "@/public/category/grade-6/science/categories.json";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

import {
  AppContent,
  AppSidebar,
  AppSidebarNav,
} from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Grade 6",
  description: "Generated by create next app",
};

export default function Grade12Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <SidebarProvider>
        <AppSidebar
          data={categories}
          teams={subjects}
          activeTeam={subjects.subjects[5]}
        />
        <SidebarInset>
          <AppSidebarNav />
          <AppContent>{children}</AppContent>
        </SidebarInset>
      </SidebarProvider>
    </div>
  );
}
