import { QuestionItem, QuestionTitle } from "@/components/courses/questions";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import Q24 from "@/datas/grade-12/english/pass-questions/2024/question1.json";
import Q25 from "@/datas/grade-12/english/pass-questions/2025/question1.json";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "ဒွါဒသမတန်း အင်္ဂလိပ်စာ ၂၀၂၄ မေးခွန်း(၁)",
  description: "Generated by create next app",
};
export default function Page() {
  const Question2024 = [...Q24.set1, ...Q24.set2, ...Q24.set3, ...Q24.set4];
  const Question2025 = [
    ...Q25.set1,
    ...Q25.set2,
    ...Q25.set3,
    ...Q25.set4,
    ...Q25.set5,
    ...Q25.set6,
    ...Q25.set7,
    ...Q25.set8,
    ...Q25.set9,
    ...Q25.set10,
  ];

  return (
    <div>
      <QuestionTitle>
        <p>I. </p>
        <p className="w-full">
          Complete the sentences with the appropriate words. The initial letters
          are given.<span className="float-end">(10 marks) </span>
        </p>
      </QuestionTitle>

      <Accordion type="multiple" className="w-full leading-0">
        {Question2024.map((data, index) => (
          <AccordionItem value={data["question-item-number"]} key={index}>
            <AccordionTrigger className="flex hover:no-underline py-1 font-normal">
              <QuestionItem>
                <p>({++index})</p>
                <p>{data["question-item-text"]}</p>
              </QuestionItem>
            </AccordionTrigger>
            <AccordionContent className="pb-2 z-0">
              <QuestionItem>No Answer</QuestionItem>
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>

      <QuestionTitle>
        <p>I. </p>
        <p className="w-full">
          Complete the sentences with the appropriate words. The initial letters
          are given.<span className="float-end">(10 marks) </span>
        </p>
      </QuestionTitle>
      {Question2025.map((data, index) => (
        <div key={index}>
          <QuestionItem>
            {/* <p>{data["question-item-number"]}</p> */}
            <p>({++index})</p>
            <p>{data["question-item-text"]}</p>
          </QuestionItem>
        </div>
      ))}
    </div>
  );
}
